Clarifies error messages.

diff --git a/gpg-reconnect-agent-session b/gpg-reconnect-agent-session
--- a/gpg-reconnect-agent-session
+++ b/gpg-reconnect-agent-session
@@ -7,7 +7,7 @@ self=`basename $0`
 # This agent info path is also specified at agent startup.
 agentinfo=$HOME/.gnupg/gpg-agent-info
 if [ ! -f $agentinfo ]; then
-  1>&2 echo "$self: agent info file not found"
+  1>&2 echo "$self: agent info file not found; failed to reconnect"
   exit 1
 fi
 source $agentinfo
@@ -15,7 +15,7 @@ source $agentinfo
 # Weird syntax to strip off everything including and after first colon.
 sockfile=${GPG_AGENT_INFO%%:*}
 if [ ! -S $sockfile ]; then
-  1>&2 echo "$self: socket not found"
+  1>&2 echo "$self: socket not found; failed to reconnect"
   exit 127
 fi
 echo "export GPG_AGENT_INFO=$GPG_AGENT_INFO"
